(()=>{'use strict';
const q=new URLSearchParams(location.search),overlayId=(q.get('id')||'').trim(),preview=q.get('preview')==='1',clientId='overlay-'+Math.random().toString(36).slice(2,10),stage=document.getElementById('stage'),previewBgToggle=document.getElementById('previewBgToggle'),connectionBadge=document.getElementById('connectionBadge');
const BROKER_URL='wss://broker.emqx.io:8084/mqtt',TOPIC_PREFIX='pixelb8/overlay/v1/';
let state=null,mqttClient=null,seededMessages=false;const seenMessages=new Set(),playedRuntimeAudio=new Set();
const PREVIEW_BGS=['dark','checker','transparent'];let previewBg='dark';
function applyPreviewBg(){if(!preview)return;document.body.classList.add('preview-mode');for(const m of PREVIEW_BGS)document.body.classList.remove('preview-bg-'+m);document.body.classList.add('preview-bg-'+previewBg);if(previewBgToggle){previewBgToggle.textContent=previewBg==='transparent'?'BG ◌':previewBg==='checker'?'BG ▦':'BG ●';previewBgToggle.title=`Preview background: ${previewBg}. Click to change.`}}
if(preview){try{const saved=localStorage.getItem('pixelb8-overlay-preview-bg');if(PREVIEW_BGS.includes(saved))previewBg=saved}catch{}applyPreviewBg();previewBgToggle?.addEventListener('click',()=>{previewBg=PREVIEW_BGS[(PREVIEW_BGS.indexOf(previewBg)+1)%PREVIEW_BGS.length];try{localStorage.setItem('pixelb8-overlay-preview-bg',previewBg)}catch{}applyPreviewBg()})}
function fit(){const s=Math.min(innerWidth/1920,innerHeight/1080);stage.style.transform=`scale(${s})`}addEventListener('resize',fit);fit();
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
function timerText(w){let sec=Number(w.seconds)||0;if(w.running&&w.startedAt)sec=Math.max(0,sec-Math.floor((Date.now()-w.startedAt)/1000));return `${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`}
const emoteUrl=id=>`https://static-cdn.jtvnw.net/emoticons/v2/${encodeURIComponent(id)}/default/dark/3.0`;
function limitedMessage(m,w){const raw=String(m.message||m.text||''),lim=Number(w.messageCharLimit)||0;if(!lim||raw.length<=lim)return{raw,limit:0};if(w.messageLimitMode==='hide')return null;return{raw,limit:lim}}
function messageBodyHtml(m,w){const info=limitedMessage(m,w);if(info===null)return null;const raw=info.raw,limit=info.limit,frags=Array.isArray(m.fragments)?m.fragments:[];if(!frags.length)return !limit?esc(raw):esc(raw.slice(0,Math.max(0,limit-3)))+'...';let used=0,out='',trimmed=false;for(const f of frags){const txt=String(f.text||'');if(limit&&used+txt.length>Math.max(0,limit-3)){const remain=Math.max(0,limit-3-used);if(remain&&f.type!=='emote')out+=esc(txt.slice(0,remain));trimmed=true;break}if(f.type==='emote'&&f.emoteId)out+=`<img class="twitchEmote" src="${emoteUrl(f.emoteId)}" style="width:${w.emoteSize||38}px;height:${w.emoteSize||38}px">`;else out+=esc(txt);used+=txt.length}if(trimmed)out+='...';return out}
function messageHtml(m,w){const body=messageBodyHtml(m,w);if(body===null)return'';const uc=/^#[0-9a-f]{6}$/i.test(m.color||'')?m.color:'#71dcff';return `<div class="msg"><span class="user" style="color:${uc};font-size:${w.usernameSize||28}px;font-weight:${w.usernameWeight||800}">${esc(m.user||m.displayName||m.userName||'chat')}:</span><span class="message" style="font-size:${w.messageSize||28}px;font-weight:${w.messageWeight||500}">${body}</span></div>`}
function itemStyle(el,w){Object.assign(el.style,{left:w.x+'px',top:w.y+'px',width:w.w+'px',height:w.h+'px','--bg':w.bg||'#06111bcc','--color':w.color||'#e8fbff','--radius':(w.borderRadius??18)+'px','--border-style':w.borderStyle||'none','--border-width':(w.borderWidth||0)+'px','--border-color':w.borderColor||'#58d9ff','--outline-style':w.outlineStyle||'none','--outline-width':(w.outlineWidth||0)+'px','--outline-color':w.outlineColor||'#000000','--font-family':`${w.fontFamily||'Inter'}, Segoe UI, Arial, sans-serif`,'--font-weight':String(w.fontWeight||600),'--font-style':w.fontStyle||'normal','--letter-spacing':(w.letterSpacing||0)+'px','--text-align':w.align||'left',fontSize:(w.fontSize||32)+'px',textAlign:w.align||'left'})}
function floatingEmote(url,w){const img=document.createElement('img');img.src=url;img.className='floatingEmote';const mn=Math.min(w.floatingMinSize||64,w.floatingMaxSize||80),mx=Math.max(w.floatingMinSize||64,w.floatingMaxSize||80),sz=mn+Math.random()*(mx-mn),dist=w.floatingDistance||600,dur=w.floatingDuration||7;Object.assign(img.style,{width:sz+'px',height:sz+'px',left:(Math.random()*100)+'vw',top:(Math.random()*100)+'vh',opacity:'1',transform:`scale(${.9+Math.random()*.2})`,transition:`transform ${Math.max(1,dur*.7)}s linear, opacity ${dur}s ease-out`});document.body.appendChild(img);requestAnimationFrame(()=>requestAnimationFrame(()=>{img.style.transform=`translate(${(Math.random()-.5)*dist}px,${(Math.random()-.5)*dist}px) scale(${.8+Math.random()*.8})`;img.style.opacity='.15'}));setTimeout(()=>img.remove(),dur*1000)}
function triggerNewEmotes(w,msgs){if(w?.visible===false)return;for(const m of msgs){if(!m?.id||seenMessages.has(m.id))continue;seenMessages.add(m.id);for(const f of Array.isArray(m.fragments)?m.fragments:[])if(f.type==='emote'&&f.emoteId)floatingEmote(emoteUrl(f.emoteId),w)}if(seenMessages.size>300){const keep=new Set(msgs.map(m=>m.id).filter(Boolean));for(const id of [...seenMessages])if(!keep.has(id))seenMessages.delete(id)}}
function renderGroup(el,w){const box=document.createElement('div');box.className='box';box.style.position='relative';box.style.width='100%';box.style.height='100%';for(const c of w.children||[]){const n=document.createElement('div');Object.assign(n.style,{position:'absolute',left:(c.x||0)+'px',top:(c.y||0)+'px',width:(c.w||100)+'px',height:(c.h||50)+'px',overflow:'hidden'});if(c.type==='image'){if(c.src)n.innerHTML=`<img src="${esc(c.src)}" style="width:100%;height:100%;object-fit:contain">`}else{n.textContent=c.text||'';Object.assign(n.style,{fontSize:(c.fontSize||32)+'px',color:c.color||'#e8fbff',display:'flex',alignItems:'center'})}box.appendChild(n)}el.appendChild(box)}
function liveRuntime(kind){const r=state?.runtime?.[kind];return r&&Number(r.expiresAt)>Date.now()?r:null}
function playRuntimeAudio(r){if(!r?.id||playedRuntimeAudio.has(r.id))return;const payload=r.audio;if(!payload)return;playedRuntimeAudio.add(r.id);const playOne=s=>{if(!s?.data)return;try{const a=new Audio(s.data);a.volume=Math.max(0,Math.min(1,Number.isFinite(Number(s.volume))?Number(s.volume):1));a.play().catch(()=>{})}catch{}};if(payload.mode==='all'&&Array.isArray(payload.sounds))payload.sounds.forEach(playOne);else playOne(payload);if(playedRuntimeAudio.size>120){const ids=[...playedRuntimeAudio];for(const id of ids.slice(0,ids.length-80))playedRuntimeAudio.delete(id)}}

function formatClock(sec){sec=Math.max(0,Math.floor(Number(sec)||0));return `${Math.floor(sec/60)}:${String(sec%60).padStart(2,'0')}`}
function renderJukebox(el,w){const j=state?.runtime?.modules?.['pixelb8.jukebox']||{};const t=j.current;if(!t){if(preview){el.innerHTML='<div class="box jukeboxBox"><div class="jbEyebrow">PIXELB8 JUKEBOX</div><div class="jbTitle">Nothing playing</div></div>';return true}return false}const dur=Math.max(0,Number(j.duration)||0),cur=Math.max(0,Number(j.currentTime)||0),pct=dur?Math.max(0,Math.min(100,cur/dur*100)):0;const next=j.queue?.[0];const visual=w.jukeboxVisualizer!==false?`<div class="jbVisualizer">${Array.from({length:18},(_,i)=>`<i style="--h:${18+((i*17+(j.visualSeed||3)*11)%70)}%"></i>`).join('')}</div>`:'';const video=w.jukeboxShowVideo!==false&&t.id?`<div class="jbVideo"><img src="https://i.ytimg.com/vi/${encodeURIComponent(t.id)}/hqdefault.jpg" alt=""></div>`:'';const over=!!video&&w.jukeboxVideoLayout==='overlay';el.innerHTML=`<div class="box jukeboxBox jb-${esc(w.jukeboxStyle||'card')} ${video?'jb-with-video':''} ${over?'jb-video-overlay':''}">${video}<div class="jbContent"><div class="jbEyebrow">PIXELB8 JUKEBOX ${j.playing?'• PLAYING':'• PAUSED'}</div><div class="jbTitle">${esc(t.title||'Unknown track')}</div>${w.jukeboxShowRequester!==false?`<div class="jbMeta">Requested by ${esc(t.user||'System')}</div>`:''}${visual}${w.jukeboxShowProgress!==false?`<div class="jbProgress"><span style="width:${pct}%"></span></div><div class="jbTime">${formatClock(cur)} / ${formatClock(dur)}</div>`:''}${w.jukeboxShowVotes!==false?`<div class="jbMeta">❤ ${Number(j.likeVotes)||0}/${Number(j.voteRequirement)||0} &nbsp; · &nbsp; ⏭ ${Number(j.skipVotes)||0}/${Number(j.voteRequirement)||0}</div>`:''}${w.jukeboxShowNext!==false?`<div class="jbNext">NEXT · ${esc(next?.title||(j.fallbackCount?'Fallback rotation':'Queue empty'))}</div>`:''}</div></div>`;return true}

function twitchClipSrc(clip,r,w){if(location.protocol!=='https:'||!clip?.id)return'';if(Number(w?.w)<400||Number(w?.h)<300)return'';const u=new URL('https://clips.twitch.tv/embed');u.searchParams.set('clip',String(clip.id));u.searchParams.set('parent',location.hostname);u.searchParams.set('autoplay',r.clipAutoplay===false?'false':'true');u.searchParams.set('muted',r.clipMuted===false?'false':'true');return u.toString()}
function warnClipAutoplay(r){if(r?.clipAutoplay!==false&&r?.clipMuted===false)console.warn('[PixelB8 Hosted Overlay] Twitch clip is set to autoplay with sound. Normal browsers may block unmuted autoplay; enable Mute clip for reliable browser testing. OBS Browser Source may behave differently.');}
function renderShoutout(el,r,w){warnClipAutoplay(r);
  if(!r){if(preview){el.innerHTML='<div class="box shoutoutBox"><div class="shoutoutProfile"><div class="shoutoutAvatarPlaceholder">TW</div><div><div class="shoutoutEyebrow">TWITCH SHOUTOUT</div><div class="shoutoutName">Shoutouts</div><div class="shoutoutMeta">Profile, channel info and optional clips appear here.</div></div></div></div>';return true}return false}
  const clip=r.clip||null,clipSrc=twitchClipSrc(clip,r,w),img=r.image||(r.showAvatar!==false?r.profileImage:'')||'',info=r.showChannelInfo!==false,game=String(r.gameName||''),title=String(r.channelTitle||''),desc=String(r.description||'');
  const clipThumb=clip?.thumbnailUrl||img||'';
  const media=clip?(clipSrc?`<div class="shoutoutMedia"><div class="shoutoutClipFallback" style="background-image:url('${esc(clipThumb)}')"></div><iframe class="twitchClipFrame" src="${esc(clipSrc)}" title="${esc(clip.title||'Twitch clip')}" width="100%" height="100%" allow="autoplay; fullscreen" allowfullscreen referrerpolicy="strict-origin-when-cross-origin"></iframe></div>`:`<div class="shoutoutMedia shoutoutMediaFallback"><div class="shoutoutClipFallback" style="background-image:url('${esc(clipThumb)}')"></div><div class="shoutoutClipBadge">${location.protocol==='https:'&&clip?.id&&(Number(w?.w)<400||Number(w?.h)<300)?'RESIZE SHOUTOUT TO 400×300+':'TWITCH CLIP'}</div></div>`):(img?`<div class="shoutoutAvatar"><img src="${esc(img)}" alt=""></div>`:'');
  el.innerHTML=`<div class="box shoutoutBox ${clip?'hasClip':''}">${media}<div class="shoutoutInfo"><div class="shoutoutEyebrow">TWITCH SHOUTOUT</div><div class="shoutoutName">${esc(r.text||`Shoutout to ${r.event?.user||'Streamer'}!`)}</div>${info&&game?`<div class="shoutoutGame">🎮 ${esc(game)}</div>`:''}${info&&title?`<div class="shoutoutTitle">${esc(title)}</div>`:''}${info&&desc&&!title?`<div class="shoutoutTitle">${esc(desc.slice(0,160))}</div>`:''}${clip?`<div class="shoutoutClipTitle">CLIP · ${esc(clip.title||'Recent clip')}${clipSrc?'':' · preview'}</div>`:''}</div></div>`;return true
}
function renderRuntimeBox(el,r,fallback){if(!r){if(preview)el.innerHTML=`<div class="box text">${esc(fallback)}</div>`;else return false;return true}playRuntimeAudio(r);const remain=Math.max(0,Number(r.expiresAt)-Date.now()),out=remain<=1000,imgDur=Number(r.imgDuration)||0,imgVisible=!imgDur||Date.now()-(Number(r.event?.ts)||Date.now())<imgDur*1000,textClass=out?(r.textOutAnim||''):(r.textInAnim||''),imgClass=out?(r.imgOutAnim||''):(r.imgInAnim||'');el.innerHTML=`<div class="box text" style="display:flex;flex-direction:column;gap:12px;align-items:center;justify-content:center;text-align:center">${r.image&&imgVisible?`<img class="runtimeAlertImage ${esc(imgClass)}" src="${esc(r.image)}" style="max-width:min(90%,${Number(r.imgSize)||320}px);max-height:65%;object-fit:contain">`:''}<div class="runtimeAlertText ${esc(textClass)}" style="font-size:${Number(r.fontSize)||44}px;color:${esc(r.fontColor||'#ffffff')};font-weight:${Number(r.fontWeight)||700};text-shadow:${esc(r.textOutline||'3px 3px 0 #000000')}">${esc(r.text||fallback)}</div></div>`;return true}
function render(){if(!state)return;const l=(state.layouts||[]).find(x=>x.id===state.activeLayoutId)||state.layouts?.[0],items=l?.widgets||[],msgs=state.twitch?.messages||[];stage.innerHTML='';const floater=items.find(w=>w.kind==='widget'&&w.type==='floating-emotes'&&w.visible!==false);if(floater)triggerNewEmotes(floater,msgs);for(const w of items){if(w.visible===false||w.type==='floating-emotes')continue;const el=document.createElement('div');el.className='w';itemStyle(el,w);let include=true;if(w.kind==='element'){const common=`style="text-align:${w.align||'left'}"`;if(w.type==='text')el.innerHTML=`<div class="box text" ${common}>${esc(w.text)}</div>`;else if(w.type==='image')el.innerHTML=`<div class="box image">${w.src?`<img src="${esc(w.src)}">`:''}</div>`;else if(w.type==='counter')el.innerHTML=`<div class="box counter"><div class="small">${esc(w.label||'COUNTER')}</div><div>${Number(w.value)||0}</div></div>`;else if(w.type==='timer')el.innerHTML=`<div class="box timer"><div class="small">${esc(w.label||'TIMER')}</div><div>${timerText(w)}</div></div>`}else if(w.type==='chat'){const shown=msgs.slice(-(w.maxMessages||8));el.innerHTML=`<div class="box chat">${shown.map(m=>messageHtml(m,w)).filter(Boolean).join('')}</div>`}else if(w.type==='group')renderGroup(el,w);else if(w.type==='alert-box')include=renderRuntimeBox(el,liveRuntime('alert'),'Alert Box');else if(w.type==='shoutouts')include=renderShoutout(el,liveRuntime('shoutout'),w);else if(w.type==='jukebox')include=renderJukebox(el,w);if(include)stage.appendChild(el)}}
let runtimePresence={alert:false,shoutout:false};
setInterval(()=>{if(!state)return;const hasTimer=(state.layouts||[]).some(l=>l.widgets?.some(w=>w.kind==='element'&&w.type==='timer'&&w.running));const nextPresence={alert:!!liveRuntime('alert'),shoutout:!!liveRuntime('shoutout')};const runtimeChanged=nextPresence.alert!==runtimePresence.alert||nextPresence.shoutout!==runtimePresence.shoutout;runtimePresence=nextPresence;if(hasTimer||runtimeChanged)render()},350);
function setConnectionStatus(text,kind=''){if(!connectionBadge)return;connectionBadge.textContent=text;connectionBadge.dataset.kind=kind;connectionBadge.hidden=!preview}
function acceptOverlayState(d){const next=d?.type==='overlay-config'?d:(d?.state&&typeof d.state==='object'?d.state:d);if(!next||typeof next!=='object'||!Array.isArray(next.layouts))return;if(!seededMessages){for(const m of next.twitch?.messages||[])if(m?.id)seenMessages.add(m.id);seededMessages=true}state=next;render()}
function connect(){if(!overlayId){setConnectionStatus('Missing overlay id','error');console.warn('[PixelB8 Hosted Overlay] Missing ?id= overlay session.');return}if(!window.mqtt?.connect){setConnectionStatus('MQTT library unavailable','error');setTimeout(connect,2000);return}const topic=TOPIC_PREFIX+overlayId;setConnectionStatus('Connecting…');try{mqttClient=window.mqtt.connect(BROKER_URL,{clientId:`pixelb8-hosted-${clientId}`,clean:true,reconnectPeriod:1800,connectTimeout:10000,keepalive:30})}catch(err){console.error('[PixelB8 Hosted Overlay] MQTT connect failed',err);setConnectionStatus('Connection failed','error');setTimeout(connect,2500);return}mqttClient.on('connect',()=>{setConnectionStatus('Connected','ok');mqttClient.subscribe(topic,{qos:0},err=>{if(err){console.error('[PixelB8 Hosted Overlay] subscribe failed',err);setConnectionStatus('Subscribe failed','error')}})});mqttClient.on('message',(incomingTopic,payload)=>{if(incomingTopic!==topic)return;try{acceptOverlayState(JSON.parse(payload.toString()))}catch(err){console.warn('[PixelB8 Hosted Overlay] Invalid state payload',err)}});mqttClient.on('reconnect',()=>setConnectionStatus('Reconnecting…'));mqttClient.on('offline',()=>setConnectionStatus('Offline','error'));mqttClient.on('error',err=>{console.warn('[PixelB8 Hosted Overlay] MQTT error',err);setConnectionStatus('Connection error','error')})}connect();
})();
